services:
  - type: web
    name: graphprobe-ai-backend
    env: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        sync: false
      - key: TG_HOST
        sync: false
      - key: TG_SECRET
        sync: false
      - key: TG_GRAPHNAME
        value: Transaction_Fraud
      - key: GOOGLE_API_KEY
        sync: false
      - key: PRODUCTION_MODE
        value: "true"
      - key: PRODUCTION_MAX_DOCS
        value: "40"
      - key: CORS_ORIGINS
        value: https://frontend-jdmw8kj8a-siris-projects-3809a50.vercel.app,https://frontend-81rdtgomo-siris-projects-3809a50.vercel.app,https://frontend-eqzjr0em9-siris-projects-3809a50c.vercel.app
